# Generated by Django 6.0.4 on 2026-05-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('otp_sent', 'OTP Sent'), ('otp_failed', 'OTP Failed'), ('otp_verified', 'OTP Verified'), ('register_completed', 'Register Completed'), ('social_login', 'Social Login')], max_length=50),
        ),
    ]
