# Generated by Django 6.0.4 on 2026-05-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_authlog_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
