# Generated by Django 6.0.4 on 2026-05-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='authlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
